# This file was generated by GoReleaser. DO NOT EDIT.
cask "a8s" do
  binary "mission-control"

  version "3.77.1"

  on_macos do
    on_arm do
      sha256 "24d0fae64b490ecaa81fbd12a058eb355b2ae1f27bf565d13abcd610dadfeadf"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5b64d24332de5188175b1b2ea6a790c948304eb1e08b63856bd7d7bb6d803902"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fd4f7b669d519c30fa023730db7a4c415ea070cfbe550a1033e2307d61e82c45"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "775f4c47ab4cd066ce47bce5eeb40d773d4c8452d56ec2668c752918826b2f71"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_linux_amd64.tar.gz"
    end
  end

  name "a8s"
  desc "Agentnetes Mission Control — the a8s CLI and mission-control daemon"
  homepage "https://agentnetes.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a8s"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/a8s"], must_succeed: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mission-control"], must_succeed: false
    end
  end

  # No zap stanza required
end
