# This file was generated by GoReleaser. DO NOT EDIT.
cask "a8s" do
  binary "mission-control"

  version "3.58.0"

  on_macos do
    on_intel do
      sha256 "0c0d3c2fdbd2499ac87853f49d8f59aeec7c68c9c7f2cfde1532ec7cc95df552"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d338e5cc1cc620c6422ba56413f1a16058daf848544c6282348bed9e857b5bc"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3797a92145fe9cf14773b5c6c80533ec01d134461b527f78c4d370f02700fd41"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "855e582e381ea91cc6b9d91746a317da959b00271871311c3e3e949892aaabd6"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_linux_arm64.tar.gz"
    end
  end

  name "a8s"
  desc "Agentnetes Mission Control — the a8s CLI and mission-control daemon"
  homepage "https://agentnetes.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a8s"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/a8s"], must_succeed: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mission-control"], must_succeed: false
    end
  end

  # No zap stanza required

end
