# This file was generated by GoReleaser. DO NOT EDIT.
cask "a8s" do
  binary "mission-control"

  version "3.70.0"

  on_macos do
    on_intel do
      sha256 "330b1c68a9f7a6f7d359b5974dcad00b23acaa2c5982ef9b9d2c5b380f6f1391"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdf47d6e82759ec6b301dbe04e4a726734d17597561f9d8f6eb0876052a40fbc"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ac99096e878841559f848fbf30f6feaca2557863afd16df7326e74ca260fade"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5cb5e16073bfc89d155883c2800b793abe03250299d126a1f9d3f3dfd0070beb"
      url "https://updates.agentnetes.io/cli/v#{version}/a8s_#{version}_linux_arm64.tar.gz"
    end
  end

  name "a8s"
  desc "Agentnetes Mission Control — the a8s CLI and mission-control daemon"
  homepage "https://agentnetes.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a8s"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/a8s"], must_succeed: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mission-control"], must_succeed: false
    end
  end

  # No zap stanza required

end
